spring.application.name=lms
spring.datasource.url=jdbc:mysql://localhost:3306/book_db
spring.datasource.username=
spring.datasource.password=

# Automatically updates the database schema matching entity classes
spring.jpa.hibernate.ddl-auto=none

# Enables the logging of SQL statements to the console
spring.jpa.show-sql=true
